### ISSUE TITLE
Can no longer use npx due to import statements in the output component.

### ISSUE THREAD

**Issue by allenpieper** [Scout24-CH/styled-svg#20]
Hey there!

Firstly, great package. I've used it on dozens of projects any time styled-components is involved. 

I use it by navigating to our icons folder and running `npx styled-svg **/*.svg`, but now the output from this relies on imports from `styled-svg` (line 4 of any generated component), which I have not installed globally or locally. I've just preferred using `npx` instead.

I tried installing it locally per the instructions, but even then I'm getting the following import error:
```
{/node_modules/styled-svg/src/helpers.js:1
(function (exports, require, module, __filename, __dirname) { import { css } from 'styled-components'

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.styled-svg (webpack:/external "styled-svg":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 0e453666b44ab1bd28e3:21:0)
    at Object../components/_icons/Download.js (/Applications/MAMP/htdocs/www/projectname/.next/dist/bundles/pages/watch/entry.js:1957:69)
    at __webpack_require__ (webpack:/webpack/bootstrap 0e453666b44ab1bd28e3:21:0)
    at Object../components/DownloadButtonDynamic.js (/Applications/MAMP/htdocs/www/projectname/.next/dist/bundles/pages/watch/entry.js:259:74)
    at __webpack_require__ (webpack:/webpack/bootstrap 0e453666b44ab1bd28e3:21:0) sourceMapsApplied: true }
```

Is `styled-svg` no longer meant to be used by `npx` in the way I've described?

I've temporarily circumvented the issue by specifying an older version of `styled-svg`:
`npx styled-svg@1.4.1 path/to/file.svg`

**Comment by jaggli** [comment]
Thank you for reporting @allenpieper 
I will take a look and fix it.
